repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0 # v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=100"]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
  - repo: https://github.com/homebysix/pre-commit-macadmin
    rev: v1.22.0 # v1.21.0
    hooks:
      - id: check-plists
      - id: check-autopkg-recipes
        args: ["--recipe-prefix=com.github.n8felton.", "--strict", "--"]
        exclude: ClustalW.pkg.recipe|Timeular.*
      - id: format-xml-plist
      - id: forbid-autopkg-overrides
      - id: forbid-autopkg-trust-info
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2 # v3.21.0
    hooks:
      - id: pyupgrade
